/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Barna.h"
#include "Barna_aliases.h"
#include "Reset_ISR.h"
#include "Clock_12KHz.h"
#include "SW_1.h"
#include "SW_1_aliases.h"
#include "Reset_Timer.h"
#include "Piros.h"
#include "Piros_aliases.h"
#include "RFID_RX.h"
#include "RFID_RX_aliases.h"
#include "Sarga.h"
#include "Sarga_aliases.h"
#include "Narancs.h"
#include "Narancs_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "RFID_ISR.h"
#include "Count_Bits.h"
#include "RFID_REG.h"
#include "Timer_1.h"
#include "P1_6.h"
#include "P1_6_aliases.h"
#include "Bootloadable.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

